<a href="https://colab.research.google.com/github/Ju-oogle/IntroDataScience/blob/Numpy/NUMPY_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analysis with **NUMPY**

## Must known about Arrays

In [89]:
import numpy as np   # Importing the library and giving it a short nickname

In [90]:
np.array([1,2,3,4,5]) # arrays must contain equal type elements

array([1, 2, 3, 4, 5])

In [91]:
a = np.array([1,2,3,4,5]) # the dimension is unchagable

## Basic functions with Arrays

In [92]:
type(a)  #  type of element in variable 'a'

numpy.ndarray

In [93]:
a.size  # To know the array's size

5

In [94]:
a.ndim  # To know the array's dimension

1

In [95]:
a.dtype  # To know the data type

dtype('int64')

In [96]:
a.shape  # Number of dimensions and num of elements in it

(5,)

## Arithmetic Operations with Arrays

In [97]:
a + 10  # Results in a new array with all the elements from array 'a' + 10

array([11, 12, 13, 14, 15])

In [98]:
a - 10  # Results in a new array with all the elements from array 'a' - 10

array([-9, -8, -7, -6, -5])

In [99]:
a * 10  # Results in a new array with all the elements from array 'a' * 10

array([10, 20, 30, 40, 50])

In [100]:
a / 10  # Results in a new array with all the elements from array 'a' / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [101]:
b = np.array([6,7,8,9,10]) # the dimension is unchagable

In [102]:
a + b  # Results in a new array with all the elements from array 'a' + 'b'

array([ 7,  9, 11, 13, 15])

In [103]:
a - b # Results in a new array with all the elements from array 'a' - 'b'

array([-5, -5, -5, -5, -5])

In [104]:
a * b # Results in a new array with all the elements from array 'a' * 'b'

array([ 6, 14, 24, 36, 50])

In [105]:
a / b # Results in a new array with all the elements from array 'a' / 'b'

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [106]:
c = np.array([1,0,1], dtype=bool) # Im determinating my array's data type
c

array([ True, False,  True])

## Auto-creation of arrays and auto-filling

In [107]:
np.arange(1,20)  # It creates an int type array with ints from start until stop -1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [108]:
np.arange(0,10,2) # Array with start - stop - steps

array([0, 2, 4, 6, 8])

In [109]:
np.zeros(10) # Array of dtype: float 0's

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [110]:
np.zeros(10, dtype=int) # Array of dtype: int 0's

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [111]:
np.zeros(3, dtype=bool) # Array of dtype: bool 0's

array([False, False, False])

In [112]:
np.ones(5) # Array of dtype: float 1's

array([1., 1., 1., 1., 1.])

In [113]:
np.ones(5, dtype=int) # Array of dtype: int 1's

array([1, 1, 1, 1, 1])

In [114]:
np.ones(3, dtype=bool) # Array of dtype: bool 1's

array([ True,  True,  True])

In [115]:
np.empty(3)  # Array filled with trashy data

array([3.06140940e-316, 1.97345609e-312, 2.33419537e-312])

In [116]:
np.empty(3, dtype=int)  # Array filled with trashy data dtype:int

array([    61963616, 399431958528, 472446402681])

In [117]:
np.empty(3, dtype=bool)  # Array filled with trashy data dtype: bool

array([ True,  True,  True])

In [118]:
np.random.randint(0,100,50) # It creates a randome selected array based on (start - end - length)

array([93, 20, 28, 85, 75, 70, 37, 16, 12, 76, 96, 31, 68, 55, 59, 44, 34,
       79, 54, 21, 64, 51, 72, 44, 67, 19, 89, 87, 68, 44, 42, 97, 60, 80,
       78, 57,  6, 19, 81, 67, 72, 18, 18, 87, 12, 15, 88, 49, 86, 48])

In [119]:
m = np.random.randint(0,10,9)
m

array([6, 6, 7, 8, 6, 4, 2, 3, 0])

In [120]:
m[0]  # Get an element from the array at the [#] indicated position

6

In [121]:
m

array([6, 6, 7, 8, 6, 4, 2, 3, 0])

In [122]:
m[4] = 6  # Reasignment of value at the [#] indicated position
m

array([6, 6, 7, 8, 6, 4, 2, 3, 0])

In [123]:
m[1:3]  # Get an array's portion at the [Start-stop-steps] position 
# If the start or the stop is included in the subrange you can ommit it.
# For ie. [0:3] == [:3]  --- [2::2] --- [2:]== [2:]

array([6, 7])

In [124]:
m[[True, False, False, True, True, False, False, True, True]] # Getting the elements from boolean instructions. True: to get it
# always same num of instructions than array's elements and extra pair of []

array([6, 8, 6, 3, 0])

## Operations with Arrays



In [125]:
def operacion(valor):
  return (valor ** 2) + 1

In [126]:
operacion(3)

10

In [127]:
m

array([6, 6, 7, 8, 6, 4, 2, 3, 0])

In [128]:
vector = np.vectorize(operacion)  # The arrays was vectorized and the function applied
vector(m)

array([37, 37, 50, 65, 37, 17,  5, 10,  1])

In [129]:
s = np.random.randint(20,30,9)
s

array([28, 24, 26, 27, 24, 29, 28, 28, 27])

In [130]:
vector = np.vectorize(lambda valor: (valor ** 2) + 1)  # For easy functions, instead of creating one, lamba can be used
vector(s)

array([785, 577, 677, 730, 577, 842, 785, 785, 730])

In [131]:
 o = np.arange(0,10)  # Original array
 o

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
p = o.copy()  # New array with the same elements than array 'o' but  if changes 
#are made, will not affect eachothers. 

In [133]:
id(o)  

139888441415600

In [134]:
id(p)   # Proof that both arrays are different even with elements look the same

139888441416080

In [135]:
a is b  # Not the same element

False

In [136]:
o[2] = 19  # Reasignment will affet only the element inside array 'o'
o

array([ 0,  1, 19,  3,  4,  5,  6,  7,  8,  9])

In [137]:
p = o.view()  # Copy of array 'o' where changes will affect both arrays. 
# You can do the same if p = o[:] p = to array 'o' form its first to its last value.
p

array([ 0,  1, 19,  3,  4,  5,  6,  7,  8,  9])

In [138]:
o is p   # Not the same element

False

In [139]:
o[-1] = 150  # Reasignment will affet both arrays 'o' & 'p'. Same if I change 'p'
o

array([  0,   1,  19,   3,   4,   5,   6,   7,   8, 150])

In [140]:
p 

array([  0,   1,  19,   3,   4,   5,   6,   7,   8, 150])

In [141]:
o is p.base  # .base points the original array

True

In [142]:
id(o)  # Proof of line 66 statement

139888441415600

In [143]:
id(p.base)  # Proof of line 66 statement. Same ID for 'o' and 'p.base'

139888441415600

## Multi-dimensional Arrays

In [144]:
A = np.array([  # 3 rows 5 columns array
  [1, 2, 3, 4, 5],
  [10, 20, 30, 40, 50],
  [100, 200, 300, 400, 500]
  ])
A

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [145]:
A.ndim  # Bidimensional array

2

In [146]:
A.shape  # (0, 1 axis) 0 -> rows 1 -> columns

(3, 5)

In [147]:
A[0][0]  # Value inserted on 1st row, 1st column

1

In [148]:
A[0,0]  # Different command to get the value inserted on 1st row, 1st column

1

In [149]:
A[1, : 3]  # Getting the first 3 elements of the 2nd row

array([10, 20, 30])

In [150]:
A[:, 3]  # All the elements for the column at the index 3

array([  4,  40, 400])

In [151]:
A[[0,2], 3]  # Getting the first and last elements for the column at the index 3

array([  4, 400])

In [152]:
A.shape

(3, 5)

## Descriptive Statistics

In [153]:
A

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [154]:
A.std()  # Returns the standard deviation along the specified axis

157.21323099535866

In [155]:
A.sum()  # Returns the result of all the elements sum

1665

In [156]:
A.min()  # Returns the minumum value findable in the array

1

In [157]:
A.max()  # Returns the maximum value findable in the array

500

In [158]:
A.mean()  # Returns the medium value / average value

111.0

In [160]:
A[1]  # Returns all the elements of row 1

array([10, 20, 30, 40, 50])

In [159]:
A[1].sum()  # Returns the addition of the elements on row 1

150

In [165]:
A[:, 2]  # 3rd column values

array([  3,  30, 300])

In [167]:
A[:, 2].mean() # Returns the 3rd column mean

111.0

In [169]:
A

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [170]:
A[:, 4].sum()  # Addition of all the values at the 5th column

555

## Array's Transposition

In [166]:
A.T # Transposition of values. To turn the rows into columns and viseversa

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300],
       [  4,  40, 400],
       [  5,  50, 500]])

In [171]:
A.T[4].sum()  # By transpose the array the addition of the values is easier to code

555

## Conditional Structures with Arrays




In [185]:
C = np.random.randint(0, 100, 50)
C

array([63, 94, 91, 74, 23, 13, 64, 24, 66,  9, 99, 52, 26, 15, 34, 34, 47,
        3, 89, 36, 79,  9, 84, 50, 94, 31, 27, 70, 56, 31, 65, 86, 18,  5,
        3,  5,  9, 44, 50, 60, 35, 97, 46, 86, 30, 58,  8, 98, 48, 63])

In [186]:
C > 50  # It compares each value with the requested condition.
# To get the list of elements instead the boolean results put the condition 
# between []

array([ True,  True,  True,  True, False, False,  True, False,  True,
       False,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True, False,  True, False, False,
        True,  True, False,  True,  True, False, False, False, False,
       False, False, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True])

In [187]:
C[C > 50] # When the condition is between [] the result is only those values 
#that correspond to it

array([63, 94, 91, 74, 64, 66, 99, 52, 89, 79, 84, 94, 70, 56, 65, 86, 60,
       97, 86, 58, 98, 63])

In [188]:
C[ (C > 50) & (C < 90) ]  # Includes more than 1 conditional. 

array([63, 74, 64, 66, 52, 89, 79, 84, 70, 56, 65, 86, 60, 86, 58, 63])

In [189]:
C[ (C == 10) | (C == 20) | (C == 50) ]   # At least 1 condition must fit

array([50, 50])

In [191]:
C

array([63, 94, 91, 74, 23, 13, 64, 24, 66,  9, 99, 52, 26, 15, 34, 34, 47,
        3, 89, 36, 79,  9, 84, 50, 94, 31, 27, 70, 56, 31, 65, 86, 18,  5,
        3,  5,  9, 44, 50, 60, 35, 97, 46, 86, 30, 58,  8, 98, 48, 63])

In [193]:
np.all(C > 50)  # All the elements must fit the condition

False

In [194]:
np.all(C >= 0)  # Returns True if all the elements fit the condition

True

In [196]:
np.any(C >= 10) # Returns True if at least 1 element fits the condition

True

## Where and select Functions

In [223]:
calificaciones = np.random.randint(1, 11, 10)
calificaciones

array([ 1,  7, 10, 10,  5, 10,  5,  9,  5,  6])

In [224]:
np.where(   # When you have max. 2 values to return to the condition 
    calificaciones >= 7, 
    'Congratulations for Passing Exam and Good Result',
    'Sorry for not Passing the Exam.',
)

array(['Sorry for not Passing the Exam.',
       'Congratulations for Passing Exam and Good Result',
       'Congratulations for Passing Exam and Good Result',
       'Congratulations for Passing Exam and Good Result',
       'Sorry for not Passing the Exam.',
       'Congratulations for Passing Exam and Good Result',
       'Sorry for not Passing the Exam.',
       'Congratulations for Passing Exam and Good Result',
       'Sorry for not Passing the Exam.',
       'Sorry for not Passing the Exam.'], dtype='<U48')

In [228]:
condiciones = [ 
    (calificaciones == 10), 
    (calificaciones == 8) | (calificaciones == 9) ,
    (calificaciones == 7),
    (calificaciones < 7),
    ]

In [229]:
opciones = [ 
    'Congratulations for Passing Exam and Getting an "A"',
    'Congratulations for Passing Exam and Good Result',
    'You Passed the Exam!',
    'Sorry for not Passing the Exam.',
]

In [230]:
calificaciones

array([ 1,  7, 10, 10,  5, 10,  5,  9,  5,  6])

In [231]:
np.select(condiciones, opciones)  # When you have more than 2 values to return to the condition 

array(['Sorry for not Passing the Exam.', 'You Passed the Exam!',
       'Congratulations for Passing Exam and Getting an "A"',
       'Congratulations for Passing Exam and Getting an "A"',
       'Sorry for not Passing the Exam.',
       'Congratulations for Passing Exam and Getting an "A"',
       'Sorry for not Passing the Exam.',
       'Congratulations for Passing Exam and Good Result',
       'Sorry for not Passing the Exam.',
       'Sorry for not Passing the Exam.'], dtype='<U51')

## Create and read documents

In [232]:
F = np.random.randint(20, 40, 10)
F

array([21, 39, 25, 37, 37, 27, 21, 23, 39, 26])

In [234]:
np.savetxt('array.txt', F)  # Name of the file, name of the array to save in the file

In [235]:
ls  # Command to see the saved files

array.txt  sample_data/


In [238]:
%load array.txt  # It shows the elements in my array in complex type

In [239]:
np.savetxt('array.txt', F, fmt='%i')  # It saves the values as int type

In [240]:
%load array.txt  # It shows the elements in my array now as int type

In [241]:
np.loadtxt('array.txt')  # Returns the info in the file as an array in Float type

array([21., 39., 25., 37., 37., 27., 21., 23., 39., 26.])

In [242]:
np.loadtxt('array.txt', dtype=int)  # 'loadtxt' creates an int type new array with the info from the file

array([21, 39, 25, 37, 37, 27, 21, 23, 39, 26])

In [246]:
np.savetxt('array.txt', F)  # 'savetxt' alters a file (Create and update the content of the file in the system)

In [247]:
F

array([21, 39, 25, 37, 37, 27, 21, 23, 39, 26])

In [248]:
F.size

10

In [251]:
g = F.reshape((2,5))
g

array([[21, 39, 25, 37, 37],
       [27, 21, 23, 39, 26]])

In [256]:
np.savetxt('matriz.csv', g, delimiter = ',', fmt='%i')  #  'savetxt' creates a file with ' ' name, 
# array to get the data from and the int type elements separated with ','  

In [257]:
ls  # To confirm that matriz.csv was created

array.txt  matriz.csv  sample_data/


In [258]:
%load matriz.csv

In [ ]:
 # 'save' and 'load' creates a binary file, the extension should be .npy

## 'Changing' Arrays

In [260]:
j = np.random.randint(100, 120, 10)
j

array([114, 110, 100, 110, 105, 106, 105, 117, 119, 108])

In [261]:
j.size

10

In [262]:
# Arrays CAN'T be changed but you can create a copy of it with the added 
np.insert(j, 4, 200)  # array to copy, index in which the value will be inserted, value

array([114, 110, 100, 110, 200, 105, 106, 105, 117, 119, 108])

In [263]:
np.append(j, 300)  # array to copy, value. It would be inserted at the end of the array

array([114, 110, 100, 110, 105, 106, 105, 117, 119, 108, 300])

In [264]:
np.delete(j, -1)  # Array to delete the value from, value's position

array([114, 110, 100, 110, 105, 106, 105, 117, 119])

In [266]:
np.resize(j, 5)  # Returns a new array with the new specified size.

array([114, 110, 100, 110, 105])

In [270]:
h = np.random.randint(200, 220, 10)
h

array([200, 201, 210, 208, 201, 209, 217, 218, 212, 219])

In [273]:
i = np.concatenate([j, h])
i

array([114, 110, 100, 110, 105, 106, 105, 117, 119, 108, 200, 201, 210,
       208, 201, 209, 217, 218, 212, 219])

In [278]:
i.sort()  # Duplicates the array and orders it from smaller to bigger
i

array([100, 105, 105, 106, 108, 110, 110, 114, 117, 119, 200, 201, 201,
       208, 209, 210, 212, 217, 218, 219])

In [279]:
i = i[::-1]  # Orders the array from bigger to smaller
i

array([219, 218, 217, 212, 210, 209, 208, 201, 201, 200, 119, 117, 114,
       110, 110, 108, 106, 105, 105, 100])